{% set name = 'tvb-data' %}
{% set version = '1.5.8' %}
{% set sha256 = "d91c3f79445ce9701bc26dd5254d09026d519f039e8b7d9fae28c78006081164" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python -m pip install . --no-deps -vv
  skip: True  # [py>27]

requirements:
  build:
    - python
  host:
    - pip
  run:
    - python

test:
  imports:
    - tvb_data

about:
  home: http://www.thevirtualbrain.com/
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: 'A package with data for TVB'
  description: |
    Various demonstration datasets for use with The Virtual Brain are provided here.
  doc_url: http://docs.thevirtualbrain.org/
  dev_url: https://github.com/the-virtual-brain/tvb-data

extra:
  recipe-maintainers:
    - liadomide
