{% set name = 'tvb-data' %}
{% set version = '2.0' %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  md5: 757760ffd852a832f43835a391377ba4
  sha256: 3a111a297d848f3d802bf7229601eb276c6776b24d360b378ac1089332e69e64
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/t/tvb-data/{{ name }}-{{ version }}.tar.gz

build:
  number: 6
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  host:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - tvb_data

about:
  home: http://www.thevirtualbrain.com/
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: 'A package with data for TVB'
  description: |
    Various demonstration datasets for use with The Virtual Brain are provided here.
  doc_url: http://docs.thevirtualbrain.org/
  dev_url: https://github.com/the-virtual-brain/tvb-data

extra:
  recipe-maintainers:
    - liadomide
