appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: F6pSoJhiDeaFX+eZ/Oqd+qpwRQFhEL4jdAs6gfunAlnANax2TVyYEfX285da2rcZh2Kqi/nDa0QDy1TIGhrWV5LrUd5y5pi0eJip3WGeRzRXlZH5SxAdFgYF4fxRupCh7XgsyJ+e4D8nPsoAh6jy1AvP+Yy9hQdfscoX5jXF1msGR107LqG3VFI8vTeOMlduKaUNTANU2twlMEeukZgtJjdIC4QdO1R6AdVJzxZknLJhMiIRRZZTnzyqVNeb7CKfiKIoUEWXtGQXQh4zM/1G/v9jJSCoLpSV0Yd0q1ZLE6plz7TwlRwPLcwADsW1C841mdjFVDUg0j6mwZBCQqk+0K0TUNd8hdhpyuzCTKn6veonvIDPQ0/OnYJaInMwoqOTcF5g3ZTcqrOommWTeoSOWhyC1XoSR9JTCATtRbN3OhKM8w/a3Pn+lyip57nW5k/k1y27wnbyJeaIwdOharFMZiJ3lA3biYjL36ZOaUUaAe18UQan0StU50SV/cMNvXSQf5f38SzkmDMi0sYcxvEDhpPrcCik5p6NJf30EKsb9uaaAbG1pme5gpA0a6ONshBeuHXH8tT5ZMEhRuqI3Oot4C20nuq7nGh7ZaHVfx1SafGcQBDeoNG+RTWM+Gr1hOv07p1SgZ6Pz6TSp1KJubVpOSX2YyWKihqVLldUlA1gv+M=}
